### ISSUE TITLE
Ubuntu 20.04 requires extra step

### ISSUE THREAD

**Issue by roger-** [Zibri/Realtek-rts5229-linux-driver#11]
I've found that `sudo dkms autoinstall` is needed on Ubuntu 20.04 for this to work.

Originally noted [here](https://gist.github.com/EndruK/a1e29e808c6436f8fd056ee3308586fa).

**Comment by Zibri** [comment]
So it is:
**sudo dkms autoinstall -m rts5229 -v 1.07**     ?

**Comment by Zibri** [comment]
Readme updated. Thanks.
