### ISSUE TITLE
How about rtsx_pci_sdmmc and rtsx_pci_ms

### ISSUE THREAD

**Issue by pepa65** [Zibri/Realtek-rts5229-linux-driver#16]
When I remove rtsx_pci from my system, it seems rtsx_pci_sdmmc and rtsx_pci_ms depend on it. Are those two no longer needed? When I tried to insert rtsx_pci_sdmmc it complained about an unknown symbol in the module, so I guess they would also need to be compiled?

After inserting rts5229 there is no kernel message when inserting an SD card.

**Comment by Zibri** [comment]
this module should not be needed in recent kernels.
if you find solutions or improvements, please do so and make a pull request,
