### ISSUE TITLE
"dkms install..." gives Error

### ISSUE THREAD

**Issue by Davros23** [Zibri/Realtek-rts5229-linux-driver#17]
Hi

#dkms install -m rts5229 -v 1.07
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/rts5229/1.07/source/dkms.conf does not exist.

#/var/lib/dkms/rts5229/1.07/source# ls
debug.h         general.h          README.txt   rtsx_chip.h  rtsx_transport.c
define.debug    Makefile           rtsx.c       rtsx.h       rtsx_transport.h
define.h        Makefile_original  rtsx_card.c  rtsx_scsi.c  sd.c
define.release  ms.c               rtsx_card.h  rtsx_scsi.h  sd.h
general.c       ms.h               rtsx_chip.c  rtsx_sys.h   trace.h

Not sure why dkms is looking in "source" dkms.conf is in the "build" directory. Any ideas?
Thanks,
D

**Comment by Zibri** [comment]
As of now I am not maintaining this.
And I think that by now it's fully supported by linux kernel.

**Comment by Zibri** [comment]
Anyway you are welcome to do a pull request, if you find a fix..

**Comment by Davros23** [comment]
Okay thanks
Will do :)
