### ISSUE TITLE
No rule to make target error

### ISSUE THREAD

**Issue by wxprofessor** [Zibri/Realtek-rts5229-linux-driver#3]
Hello :)

After spending an inordinate amount of time trying to get the sd card reader working in my old Alienware Area-51 R2 (formerly windows 10 now, ubuntu) ... I downloaded the latest version from realtek and ran into the "#include <linux/vmalloc.h>" errors, which I fixed by adjusting the various *.c files... unfortunately with that version, and yours I end up with the same error as follows:

`patrick@Area-51-R2:~/Downloads/realtek/Realtek-rts5229-linux-driver$ sudo make

cp -f ./define.release ./define.h
make -C /lib/modules/4.13.0-46-generic/build/ SUBDIRS= modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-46-generic'
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/include/generated/asm/syscalls_32.h'.  Stop.
arch/x86/Makefile:253: recipe for target 'archheaders' failed
make[1]: *** [archheaders] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-46-generic'
Makefile:35: recipe for target 'default' failed
make: *** [default] Error 2`

have you found a workaround? :)

fyi

` uname -a
Linux Area-51-R2 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Cheers,

--patrick

**Comment by Zibri** [comment]
It seems that the driver in the staging directory works.

/kernel/drivers/staging/rts5208/rts5208.ko

give that a try

**Comment by wxprofessor** [comment]
heh :)  

![image](https://user-images.githubusercontent.com/5704029/44987540-8861ec80-af55-11e8-9465-41479e5355ab.png)

it's all good... i have a new box on the way and an old rosewill that i will throw into it :)

**Comment by wxprofessor** [comment]
fyi for those with similar problems in the future... this installed properly, but I still can't read my SD card.. it could of course be a hardware issue, but it got me further :)

https://github.com/asymingt/rts5139
