### ISSUE TITLE
Requires running "sudo update-initramfs -u" after install on Kubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [Zibri/Realtek-rts5229-linux-driver#8]

**Comment by ahstram** [comment]
I suspect I saw the same issue with Ubuntu 18.04.3 LTS. Cannot confirm 100% that running `sudo update-initramfs -u` is what fixed my issue, but it is one of the things I did which ended up in allowing the driver to work.

**Comment by Zibri** [comment]
added to readme.txt
